# Generated by ariadne-codegen
# Source: app/graphql/queries

from typing import Any

from .async_base_client import AsyncBaseClient
from .base_model import UNSET, UnsetType
from .get_order_details import GetOrderDetails, GetOrderDetailsOrder
from .list_recent_orders import ListRecentOrders, ListRecentOrdersOrders


def gql(q: str) -> str:
    return q


class ShopifyClient(AsyncBaseClient):
    async def get_order_details(
        self, id: str, **kwargs: Any
    ) -> GetOrderDetailsOrder | None:
        query = gql(
            """
            query GetOrderDetails($id: ID!) {
              order(id: $id) {
                id
                name
                legacyResourceId
                createdAt
                displayFulfillmentStatus
                customer {
                  firstName
                  lastName
                  email
                }
                lineItems(first: 50) {
                  edges {
                    node {
                      id
                      title
                      variantTitle
                      quantity
                      originalUnitPriceSet {
                        shopMoney {
                          amount
                          currencyCode
                        }
                      }
                      customAttributes {
                        key
                        value
                      }
                    }
                  }
                }
              }
            }
            """
        )
        variables: dict[str, object] = {"id": id}
        response = await self.execute(
            query=query, operation_name="GetOrderDetails", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetOrderDetails.model_validate(data).order

    async def list_recent_orders(
        self, first: int, query: str | None | UnsetType = UNSET, **kwargs: Any
    ) -> ListRecentOrdersOrders:
        _query = gql(
            """
            query ListRecentOrders($first: Int!, $query: String) {
              orders(first: $first, query: $query, sortKey: CREATED_AT, reverse: true) {
                edges {
                  node {
                    id
                    name
                    legacyResourceId
                    createdAt
                    email
                    customer {
                      firstName
                      lastName
                    }
                  }
                }
              }
            }
            """
        )
        variables: dict[str, object] = {"first": first, "query": query}
        response = await self.execute(
            query=_query,
            operation_name="ListRecentOrders",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return ListRecentOrders.model_validate(data).orders
