# Generated by ariadne-codegen
# Source: app/graphql/queries

from typing import Any

from pydantic import Field

from .base_model import BaseModel
from .enums import CurrencyCode, OrderDisplayFulfillmentStatus


class GetOrderDetails(BaseModel):
    order: GetOrderDetailsOrder | None


class GetOrderDetailsOrder(BaseModel):
    id: str
    name: str
    legacy_resource_id: Any = Field(alias="legacyResourceId")
    created_at: Any = Field(alias="createdAt")
    display_fulfillment_status: OrderDisplayFulfillmentStatus = Field(
        alias="displayFulfillmentStatus"
    )
    customer: GetOrderDetailsOrderCustomer | None
    line_items: GetOrderDetailsOrderLineItems = Field(alias="lineItems")


class GetOrderDetailsOrderCustomer(BaseModel):
    first_name: str | None = Field(alias="firstName")
    last_name: str | None = Field(alias="lastName")
    email: str | None


class GetOrderDetailsOrderLineItems(BaseModel):
    edges: list[GetOrderDetailsOrderLineItemsEdges]


class GetOrderDetailsOrderLineItemsEdges(BaseModel):
    node: GetOrderDetailsOrderLineItemsEdgesNode


class GetOrderDetailsOrderLineItemsEdgesNode(BaseModel):
    id: str
    title: str
    variant_title: str | None = Field(alias="variantTitle")
    quantity: int
    original_unit_price_set: (
        GetOrderDetailsOrderLineItemsEdgesNodeOriginalUnitPriceSet
    ) = Field(alias="originalUnitPriceSet")
    custom_attributes: list[
        GetOrderDetailsOrderLineItemsEdgesNodeCustomAttributes
    ] = Field(alias="customAttributes")


class GetOrderDetailsOrderLineItemsEdgesNodeOriginalUnitPriceSet(BaseModel):
    shop_money: (
        GetOrderDetailsOrderLineItemsEdgesNodeOriginalUnitPriceSetShopMoney
    ) = Field(alias="shopMoney")


class GetOrderDetailsOrderLineItemsEdgesNodeOriginalUnitPriceSetShopMoney(BaseModel):
    amount: Any
    currency_code: CurrencyCode = Field(alias="currencyCode")


class GetOrderDetailsOrderLineItemsEdgesNodeCustomAttributes(BaseModel):
    key: str
    value: str | None


GetOrderDetails.model_rebuild()
GetOrderDetailsOrder.model_rebuild()
GetOrderDetailsOrderLineItems.model_rebuild()
GetOrderDetailsOrderLineItemsEdges.model_rebuild()
GetOrderDetailsOrderLineItemsEdgesNode.model_rebuild()
GetOrderDetailsOrderLineItemsEdgesNodeOriginalUnitPriceSet.model_rebuild()
