# Generated by ariadne-codegen
# Source: app/graphql/queries

from typing import Any

from pydantic import Field

from .base_model import BaseModel


class ListRecentOrders(BaseModel):
    orders: ListRecentOrdersOrders


class ListRecentOrdersOrders(BaseModel):
    edges: list[ListRecentOrdersOrdersEdges]


class ListRecentOrdersOrdersEdges(BaseModel):
    node: ListRecentOrdersOrdersEdgesNode


class ListRecentOrdersOrdersEdgesNode(BaseModel):
    id: str
    name: str
    legacy_resource_id: Any = Field(alias="legacyResourceId")
    created_at: Any = Field(alias="createdAt")
    email: str | None
    customer: ListRecentOrdersOrdersEdgesNodeCustomer | None


class ListRecentOrdersOrdersEdgesNodeCustomer(BaseModel):
    first_name: str | None = Field(alias="firstName")
    last_name: str | None = Field(alias="lastName")


ListRecentOrders.model_rebuild()
ListRecentOrdersOrders.model_rebuild()
ListRecentOrdersOrdersEdges.model_rebuild()
ListRecentOrdersOrdersEdgesNode.model_rebuild()
