# Generated by ariadne-codegen
# Source: app/graphql/queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import OrderDisplayFinancialStatus


class ListRecentOrders(BaseModel):
    orders: "ListRecentOrdersOrders"


class ListRecentOrdersOrders(BaseModel):
    edges: list["ListRecentOrdersOrdersEdges"]


class ListRecentOrdersOrdersEdges(BaseModel):
    node: "ListRecentOrdersOrdersEdgesNode"


class ListRecentOrdersOrdersEdgesNode(BaseModel):
    id: str
    name: str
    legacy_resource_id: Any = Field(alias="legacyResourceId")
    created_at: Any = Field(alias="createdAt")
    email: Optional[str]
    display_financial_status: Optional[OrderDisplayFinancialStatus] = Field(
        alias="displayFinancialStatus"
    )
    customer: Optional["ListRecentOrdersOrdersEdgesNodeCustomer"]
    shipping_line: Optional["ListRecentOrdersOrdersEdgesNodeShippingLine"] = Field(
        alias="shippingLine"
    )


class ListRecentOrdersOrdersEdgesNodeCustomer(BaseModel):
    first_name: Optional[str] = Field(alias="firstName")
    last_name: Optional[str] = Field(alias="lastName")


class ListRecentOrdersOrdersEdgesNodeShippingLine(BaseModel):
    title: str


ListRecentOrders.model_rebuild()
ListRecentOrdersOrders.model_rebuild()
ListRecentOrdersOrdersEdges.model_rebuild()
ListRecentOrdersOrdersEdgesNode.model_rebuild()
