"""add_job_id_columns

Revision ID: 59d0e8a1b461
Revises: 4bf86552fe5b
Create Date: 2026-01-18 02:45:08.742903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '59d0e8a1b461'
down_revision: Union[str, None] = '4bf86552fe5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coloring_versions', sa.Column('runpod_job_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('svg_versions', sa.Column('vectorizer_job_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('svg_versions', 'vectorizer_job_id')
    op.drop_column('coloring_versions', 'runpod_job_id')
    # ### end Alembic commands ###
