import { SHOPIFY_STORE_HANDLE, SHOPIFY_ADMIN_BASE_URL } from "./config";
import {
  listOrders as _listOrders,
  getOrder as _getOrder,
  getOrderImage as _getOrderImage,
  syncOrder as _syncOrder,
  fetchFromShopify as _fetchFromShopify,
  generateOrderColoring as _generateOrderColoring,
  generateImageColoring as _generateImageColoring,
  generateOrderSvg as _generateOrderSvg,
  generateImageSvg as _generateImageSvg,
  selectVersion as _selectVersion,
  retryVersion as _retryVersion,
} from "@/api/generated/orders/orders";
import type {
  OrderListResponse,
  OrderDetailResponse,
  ImageResponse,
  StatusResponse,
  ColoringVersionResponse,
  SvgVersionResponse,
  GenerateColoringResponse,
  GenerateSvgResponse,
  GenerateColoringRequest,
  GenerateSvgRequest,
} from "@/api/generated/schemas";
import { VersionType } from "@/api/generated/schemas";

// =============================================================================
// URL Helpers (keep these - not generated by Orval)
// =============================================================================

export function getShopifyOrderUrl(shopifyId: number): string {
  return `${SHOPIFY_ADMIN_BASE_URL}/${SHOPIFY_STORE_HANDLE}/orders/${shopifyId}`;
}

// =============================================================================
// Re-export Generated Types with cleaner names
// =============================================================================

export type {
  OrderResponse as Order,
  OrderListResponse,
  OrderDetailResponse as OrderDetail,
  OrderStatus,
  LineItemResponse as LineItem,
  ImageResponse as OrderImage,
  ColoringVersionResponse as ColoringVersion,
  SvgVersionResponse as SvgVersion,
  SelectedVersionIdsResponse as SelectedVersionIds,
  VersionsResponse as Versions,
  ColoringOptionsResponse as ColoringOptions,
  SvgOptionsResponse as SvgOptions,
  ColoringProcessingStatus,
  SvgProcessingStatus,
  GenerateColoringRequest as ColoringSettings,
  GenerateSvgRequest as SvgSettings,
  GenerateColoringResponse,
  GenerateSvgResponse,
  StatusResponse,
} from "@/api/generated/schemas";

export { VersionType };

// =============================================================================
// Helper to extract data from Orval response (assumes success or throws)
// =============================================================================

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function extractData<T>(response: any): T {
  // The customFetch already throws on non-ok responses,
  // so we can safely assume success here and extract the data
  return response.data as T;
}

// =============================================================================
// API Functions (extract data from Orval response wrappers)
// =============================================================================

/**
 * Fetch list of orders with pagination
 */
export async function fetchOrders(skip = 0, limit = 50): Promise<OrderListResponse> {
  const response = await _listOrders({ skip, limit });
  return extractData(response) as OrderListResponse;
}

/**
 * Fetch a single order with line items and images by Order ID (ULID)
 */
export async function fetchOrder(orderId: string): Promise<OrderDetailResponse> {
  const response = await _getOrder(orderId);
  return extractData(response) as OrderDetailResponse;
}

/**
 * Fetch a single image with all coloring/SVG versions
 */
export async function fetchImage(orderId: string, imageId: number): Promise<ImageResponse> {
  const response = await _getOrderImage(orderId, imageId);
  return extractData(response) as ImageResponse;
}

/**
 * Trigger a manual sync/re-processing of an order
 */
export async function syncOrder(orderId: string): Promise<StatusResponse> {
  const response = await _syncOrder(orderId);
  return extractData(response) as StatusResponse;
}

/**
 * Queue a background task to fetch recent orders from Shopify
 */
export async function fetchFromShopify(limit = 20): Promise<StatusResponse> {
  const response = await _fetchFromShopify({ limit });
  return extractData(response) as StatusResponse;
}

/**
 * Generate coloring books for all images in an order
 */
export async function generateOrderColoring(
  orderId: string,
  settings?: GenerateColoringRequest | null
): Promise<GenerateColoringResponse> {
  const response = await _generateOrderColoring(orderId, settings ?? null);
  return extractData(response) as GenerateColoringResponse;
}

/**
 * Generate a coloring book for a single image
 */
export async function generateImageColoring(
  imageId: number,
  settings?: GenerateColoringRequest | null
): Promise<ColoringVersionResponse> {
  const response = await _generateImageColoring(imageId, settings ?? null);
  return extractData(response) as ColoringVersionResponse;
}

/**
 * Generate SVGs for all images in an order
 */
export async function generateOrderSvg(
  orderId: string,
  settings?: GenerateSvgRequest | null
): Promise<GenerateSvgResponse> {
  const response = await _generateOrderSvg(orderId, settings ?? null);
  return extractData(response) as GenerateSvgResponse;
}

/**
 * Generate an SVG for a single image
 */
export async function generateImageSvg(
  imageId: number,
  settings?: GenerateSvgRequest | null
): Promise<SvgVersionResponse> {
  const response = await _generateImageSvg(imageId, settings ?? null);
  return extractData(response) as SvgVersionResponse;
}

/**
 * Select a coloring version as the default for an image
 */
export async function selectColoringVersion(
  imageId: number,
  versionId: number
): Promise<StatusResponse> {
  const response = await _selectVersion(imageId, VersionType.coloring, versionId);
  return extractData(response) as StatusResponse;
}

/**
 * Select an SVG version as the default for an image
 */
export async function selectSvgVersion(
  imageId: number,
  versionId: number
): Promise<StatusResponse> {
  const response = await _selectVersion(imageId, VersionType.svg, versionId);
  return extractData(response) as StatusResponse;
}

/**
 * Retry a failed coloring version generation
 */
export async function retryColoringVersion(
  imageId: number,
  versionId: number
): Promise<ColoringVersionResponse> {
  const response = await _retryVersion(imageId, VersionType.coloring, versionId);
  return extractData(response) as ColoringVersionResponse;
}

/**
 * Retry a failed SVG version generation
 */
export async function retrySvgVersion(
  imageId: number,
  versionId: number
): Promise<SvgVersionResponse> {
  const response = await _retryVersion(imageId, VersionType.svg, versionId);
  return extractData(response) as SvgVersionResponse;
}

// =============================================================================
// Re-export Generated Hooks and Query Keys
// =============================================================================

export {
  // Query hooks
  useListOrders,
  useGetOrder,
  useGetOrderImage,
  // Mutation hooks
  useSyncOrder,
  useFetchFromShopify,
  useGenerateOrderColoring,
  useGenerateImageColoring,
  useGenerateOrderSvg,
  useGenerateImageSvg,
  useSelectVersion,
  useRetryVersion,
  // Query key functions
  getListOrdersQueryKey,
  getGetOrderQueryKey,
  getGetOrderImageQueryKey,
} from "@/api/generated/orders/orders";
